site_name: Spello Consulting Utility Library
site_url: https://github.com/NickElseySpelloC/sc_utility

theme:
  name: material

plugins:
  - search
  - include-markdown
  - mkdocstrings:
      handlers:
        python:
          paths:
            - src
          options:
            docstring_style: google  # or numpy, sphinx
            show_source: false
            heading_level: 2

nav:
  - Home: index.md
  - Getting Started: 
      - Using the Library: guide/getting_started.md
      - Shelly Smart Switches: guide/shelly_control.md
      - Shelly Models Library: guide/shelly_models_list.md
      - Shelly Control Object Reference: guide/shelly_control_objects.md
  - API Reference:
      - Common Utilities: reference/common.md
      - CSVReader: reference/csvreader.md
      - DateHelper: reference/datehelper.md
      - ExcelReader: reference/excelreader.md
      - WeatherClient: reference/weather_client.md
      - JSONEncoder: reference/jsonencoder.md
      - SCConfigManager: reference/configmanager.md
      - SCLogging: reference/logging.md
      - ShellyControl: reference/shelly_control.md
